<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="
           http://maven.apache.org/POM/4.0.0
           https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.6</version>
        <relativePath/>
    </parent>

    <groupId>com.monkey</groupId>
    <artifactId>monkey-ams</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <packaging>pom</packaging>

    <name>monkey-ams</name>
    <description>Spring Boot + Dubbo + ZooKeeper + Apollo 微服务项目</description>

    <properties>
        <java.version>21</java.version>
        <dubbo.version>3.3.5</dubbo.version>
        <ams-common.version>1.0.0-SNAPSHOT</ams-common.version>
        <order-bsm-biz-api.version>1.0.0-SNAPSHOT</order-bsm-biz-api.version>
        <acq-bsm-biz-api.version>1.0.0-SNAPSHOT</acq-bsm-biz-api.version>
        <user-bsm-biz-api.version>1.0.0-SNAPSHOT</user-bsm-biz-api.version>
        <account-bsm-biz-api.version>1.0.0-SNAPSHOT</account-bsm-biz-api.version>
        <redisson.version>3.52.0</redisson.version>
        <monkey-common-lock.version>1.0.0-SNAPSHOT</monkey-common-lock.version>
        <monkey-common-mq.version>1.0.0-SNAPSHOT</monkey-common-mq.version>
        <monkey-common-auth.verison>1.0.0-SNAPSHOT</monkey-common-auth.verison>
        <commons-collections4.version>4.5.0</commons-collections4.version>
    </properties>

    <modules>

        <module>order-bsm-biz</module>
        <module>acq-bsm-biz</module>
        <module>ams-common</module>
        <module>ams-app</module>
        <module>user-bsm-biz</module>
        <module>account-bsm-biz</module>
        <module>monkey-common-lock</module>
        <module>monkey-common-mq</module>
        <module>monkey-common-auth</module>
    </modules>

    <dependencyManagement>

        <dependencies>

            <!-- Dubbo -->
            <dependency>
                <groupId>org.apache.dubbo</groupId>
                <artifactId>dubbo-spring-boot-starter</artifactId>
                <version>${dubbo.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.dubbo</groupId>
                <artifactId>dubbo-nacos-spring-boot-starter</artifactId>
                <version>${dubbo.version}</version>
            </dependency>

        </dependencies>

    </dependencyManagement>


</project>