spring.application.name=order-bsm-biz-service
app.id=order-bsm-biz-service
server.port=8080
apollo.meta=http://apollo-configservice-dev:8080
# 直接指定 ConfigService，避免拿到 Docker 内网 IP
apollo.config-service=http://apollo-configservice-dev:8080
# 关键配置：指定 Apollo 为配置中心
# dubbo.config-center.address=http://host.docker.internal:8080
apollo.bootstrap.enabled=true
apollo.bootstrap.eagerLoad.enabled=true
