spring.application.name=ams-app
server.port=8081

# Dubbo（作为消费者通过注册中心调用 user-bsm-biz-service）
dubbo.application.name=ams-app
dubbo.application.qos-enable=false
dubbo.registry.address=zookeeper://localhost:2181
